[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Production context: all deploys from the Production branch set in your site's
# deploy contexts will inherit these settings.
[context.production]

